@BaseAddress=http://localhost:8000

### Health Check
GET {{BaseAddress}}/status
Accept: application/json


### GET Convert
GET {{BaseAddress}}/convert?from_currency=USD&to_currency=EUR&amount=100
Accept: application/json


### POST Convert 
POST {{BaseAddress}}/convert
Accept: application/json
Content-Type: application/json

{
  "from_currency": "USD",
  "to_currency": "JPY",
  "amount": 50
}