@BaseAddress=http://localhost:8000

### Health Check
GET {{BaseAddress}}/status
Accept: application/json


### Convert
GET {{BaseAddress}}/convert?from_currency=USD&to_currency=INR&amount=100
Accept: application/json

